### ISSUE TITLE
Nodes randomly go offline and don't reconnect..

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1948] opened 2017-03-07 21:08 UTC
I have a master that is in one datacenter and seven nodes in another datacenter. The `kontena node ls` command shows currently two nodes offline. Restarting kontena-agent service on the nodes causes them to reconnect and come back online, but as the connection is not actually broken they should have reconnected themselves.

```
$ kontena node ls
  Name                                                                   Version    Status     Initial    Labels
⊗ app2                                                                   1.1.2      online     1 / 4      region=chi,app,frontend
⊝ app1                                                                   1.1.2      offline    2 / 4      region=chi,app,frontend
⊝ admin1                                                                 1.1.2      offline    3 / 4      region=chi,admin,app,nfs
⊗ db2                                                                    1.1.2      online     4 / 4      region=chi,db,db-node
⊛ app3                                                                   1.1.2      online     -          region=chi,app,frontend
⊛ db3                                                                    1.1.2      online     -          region=chi,db,db-node
⊛ db1                                                                    1.1.2      online     -          region=chi,db,db-node
```

```
$ docker logs --tail 100 kontena-agent
----------------/// Lots of lines like:
I, [2017-03-07T12:58:36.632891 #1]  INFO -- Kontena::ServicePods::Creator: creating service: redis-session.lb-2
I, [2017-03-07T12:58:37.228617 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: quay.io/xxx/xxx:galera-lb-latest
----------------/// and then this:
I, [2017-03-07T12:59:08.453206 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1000
I, [2017-03-07T12:59:08.555961 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://mgr.sys.bss-llc.com
I, [2017-03-07T12:59:13.710580 #1]  INFO -- Kontena::WebsocketClient: connection established
E, [2017-03-07T12:59:18.333473 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "launch-router", "--ipalloc-range", "", "--dns-domain", "kontena.local", "--password", "<redacted>", "--trusted-subnets", "10.36.18.0/24"]
weave is already running; you can stop it with 'weave stop-router'.

I, [2017-03-07T12:59:18.660642 #1]  INFO -- Kontena::NetworkAdapters::Weave: router connected to peers 10.36.18.164, 10.36.18.67, 10.36.18.99, 10.36.18.163, 10.36.18.98, 10.36.18.66
I, [2017-03-07T12:59:19.063684 #1]  INFO -- Kontena::NetworkAdapters::Weave: Exposed host node at cidr=10.81.0.3/16
I, [2017-03-07T12:59:20.817510 #1]  INFO -- Kontena::WebsocketClient: did not receive pong, closing connection
I, [2017-03-07T12:59:20.818333 #1]  INFO -- Kontena::Workers::QueueWorker: stopped processing of msg queue
I, [2017-03-07T12:59:20.819733 #1]  INFO -- Kontena::Workers::LogWorker: stopped log streaming
I, [2017-03-07T12:59:21.593406 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1000
I, [2017-03-07T12:59:21.717507 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://mgr.sys.bss-llc.com
I, [2017-03-07T12:59:21.984582 #1]  INFO -- Kontena::WebsocketClient: connection established
I, [2017-03-07T12:59:24.436873 #1]  INFO -- Kontena::Workers::QueueWorker: started to process msg queue
I, [2017-03-07T12:59:24.439224 #1]  INFO -- Kontena::Workers::LogWorker: started log streaming
E, [2017-03-07T12:59:24.804336 #1] ERROR -- Kontena::NetworkAdapters::WeaveExecutor: weaveexec exit 1: ["--local", "launch-router", "--ipalloc-range", "", "--dns-domain", "kontena.local", "--password", "<redacted>", "--trusted-subnets", "10.36.18.0/24"]
weave is already running; you can stop it with 'weave stop-router'.

I, [2017-03-07T12:59:25.099196 #1]  INFO -- Kontena::NetworkAdapters::Weave: router connected to peers 10.36.18.164, 10.36.18.67, 10.36.18.99, 10.36.18.163, 10.36.18.98, 10.36.18.66
I, [2017-03-07T12:59:25.424263 #1]  INFO -- Kontena::NetworkAdapters::Weave: Exposed host node at cidr=10.81.0.3/16
E, [2017-03-07T16:59:26.050171 #1] ERROR -- Kontena::Workers::EventWorker: connection timeout... retrying
E, [2017-03-07T20:59:26.322830 #1] ERROR -- Kontena::Workers::EventWorker: connection timeout... retrying
```
These last three log entries are 4 hours apart from each other and the last one actually was logged while I had ping running and was getting consistent ping.

The connection between node and master is very solid:
```
$ ping <master_ip>
...
--- <master_ip> ping statistics ---
124 packets transmitted, 124 received, 0% packet loss, time 123220ms
rtt min/avg/max/mdev = 23.665/23.768/24.052/0.059 ms
```

After I run `docker restart kontena-agent` the node reconnects immediately with no problem.

**Comment by SpComb** [comment] 2017-03-09 09:10
Can you show the master node's `docker logs kontena-master-api` server logs, in particular any `node opened connection` and `node closed connection` messages related to the node that you pasted the `kontena-agent` logs from? What's the timing of the server's connection messages compared to what the agent logs during the same time period?

> ```
> E, [2017-03-07T16:59:26.050171 #1] ERROR -- Kontena::Workers::EventWorker: connection timeout... retrying
> E, [2017-03-07T20:59:26.322830 #1] ERROR -- Kontena::Workers::EventWorker: connection timeout... retrying
> ```

These `EventWorker` errors are related to the local Docker API, not the agent-server websocket connection to the master.

**Comment by SpComb** [comment] 2017-03-10 08:56
I suspect that this may be a problem in either the master `kontena-server-haproxy` or `kontena-server-api`, and it would be good too see the `docker logs` of those from the master node when this is happening.

This could be a re-occurence of the underlying issues in #1626, but the server still isn't recovering from those correctly.

**Comment by SpComb** [comment] 2017-03-13 14:40
There's some indication of mongodb errors in the server logs when this is happening:

```
E, [2017-03-09T22:08:06.669353 #7] ERROR -- Agent::MessageHandler: KeyError: key not found: "a"

E, [2017-03-09T22:08:06.670107 #7] ERROR -- Agent::MessageHandler: /usr/lib/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/registry.rb:43:in `fetch'
/usr/lib/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/registry.rb:43:in `get'
/usr/lib/ruby/gems/2.3.0/gems/bson-3.2.6/lib/bson/hash.rb:79:in `from_bson'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:134:in `block (2 levels) in read'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:133:in `times'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:133:in `each'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:133:in `map'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:133:in `block in read'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:225:in `with_connection'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:115:in `read'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/protocol/query.rb:213:in `receive_replies'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:153:in `block in receive_replies'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:152:in `map'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/connection.rb:152:in `receive_replies'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:605:in `block (2 levels) in flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:193:in `block in ensure_connected'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:118:in `block in connection'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:64:in `block (2 levels) in with'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `handle_interrupt'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:63:in `block in with'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/usr/lib/ruby/gems/2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:116:in `connection'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:189:in `ensure_connected'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:603:in `block in flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:632:in `block in logging'
/usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `block in instrument'
/usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/notifications.rb:159:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/instrumentable.rb:31:in `instrument'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:631:in `logging'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:602:in `flush'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:406:in `process'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/operation/read.rb:48:in `execute'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:663:in `read'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:426:in `query'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:129:in `block in first'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:249:in `block in with_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:219:in `block in ensure_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/executable.rb:25:in `execute'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/node.rb:218:in `ensure_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/cluster.rb:248:in `with_primary'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:55:in `block in with_node'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/retryable.rb:30:in `with_retry'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/read_preference/primary.rb:54:in `with_node'
/usr/lib/ruby/gems/2.3.0/gems/moped-2.0.7/lib/moped/query.rb:128:in `first'
/app/app/services/agent/message_handler.rb:246:in `grid_container'
/app/app/services/agent/message_handler.rb:233:in `cached_container'
/app/app/services/agent/message_handler.rb:110:in `on_container_log'
/app/app/services/agent/message_handler.rb:60:in `handle_message'
/app/app/services/agent/message_handler.rb:28:in `block (2 levels) in run'
/app/app/services/agent/message_handler.rb:25:in `loop'
/app/app/services/agent/message_handler.rb:25:in `block in run'
```

This kind of error seems to indicate that the server is reading corrupted data from the mongodb socket, with random invalid BSON types: https://github.com/mongoid/moped/issues/305

There's some indication that this is related to threading and mongodb connections: https://jira.mongodb.org/browse/MONGOID-3855

> After a few hours of debugging, I think I got the culprit here for me. I couldn't repro in a rails console, only in a Unicorn web server. For us, we make some extra connections to other sessions in an after_initialize block in Rails. I had to call disconnect those as well, and since then I haven't been able to reproduce.

Which thus looks like #1964 may be the underlying issue... My guess is that multiple server threads end up sharing the same mongodb connection socket, which may then result in random query result corruption.

**Comment by SpComb** [comment] 2017-03-28 08:51
It seems that 1.1.5 with the referenced Moped fixes has not solved this issue... more complete master/agent logs in https://github.com/kontena/kontena/issues/2025

> Master/Node Version: 1.1.5
> [kontena-server-api.txt](https://github.com/kontena/kontena/files/873032/kontena-server-api.txt)
> [kontena-agent.txt](https://github.com/kontena/kontena/files/873033/kontena-agent.txt)

**Comment by SpComb** [comment] 2017-03-28 09:06
@colinmollenhour Which named host node are those agent logs from?

**Comment by SpComb** [comment] 2017-03-28 10:10
What does the CPU utilization on the server and agent look like? Does it go up and start hitting 100% when this kind of meltdown happens?

The root cause of this kind of behavior is probably going to be overloaded server that just can't keep up with the agent RPCs. In one case, this was caused by a service that was spamming container logs via Docker in a tightloop.

**Comment by colinmollenhour** [comment] 2017-03-28 22:47
> Which named host node are those agent logs from?

The kontena-agent.txt file is from app3.

> What does the CPU utilization on the server and agent look like? Does it go up and start hitting 100% when this kind of meltdown happens?

No, I have not seen any 100% CPU usage scenarios. Here is the CPU usage and load average for the period covering #2025 report: https://www.screencast.com/t/cskCAwsN

**Comment by SpComb** [comment] 2017-03-29 08:54
> No, I have not seen any 100% CPU usage scenarios. Here is the CPU usage and load average for the period covering #2025 report: https://www.screencast.com/t/cskCAwsN

Is that from the agent or the server? Assuming the agent, what does the master node's CPU util look like?

**Comment by colinmollenhour** [comment] 2017-03-29 15:05
Sorry, that was the master. The agent didn't have any odd CPU usage either, in fact it was hardly above 0.1% all weekend because it is just idle.

**Comment by SpComb** [comment] 2017-04-11 10:29
The logs show multiple open websocket connections for `app3` after the agent restarts at `00:52:45`:

```
{"log":"I, [2017-03-27T00:52:47.075842 #7]  INFO -- WebsocketBackend: node opened connection: app3, labels: [\"region=singlehop-chi\"]\n","stream":"stdout","time":"2017-03-27T00:52:47.076149191Z"}
{"log":"I, [2017-03-27T00:52:47.480824 #11]  INFO -- WebsocketBackend: node opened connection: app3, labels: [\"region=singlehop-chi\"]\n","stream":"stdout","time":"2017-03-27T00:52:47.481211397Z"}
{"log":"I, [2017-03-27T00:53:08.492946 #7]  INFO -- WebsocketBackend: node closed connection: app3\n","stream":"stdout","time":"2017-03-27T00:53:08.495699778Z"}
```

So at this point, it seems like the agent has an active connection open with worker `#11`, but the other worker `#7` has raced with that one, and unplugged the node, explicitly marking it as `:connected => false`.

The active `#11` `WebsocketBackend` will send keepalive pings to the agent, and then invoke `on_pong` with the mistakenly disconnected `HostNode`... however, it looks like the `on_pong` `!connected?` case has a tragic bug: https://github.com/kontena/kontena/blob/v1.1.5/server/app/middlewares/websocket_backend.rb#L257

```ruby
      if node.connected?
        ...
      else
        grid = Grid.find_by(node_id: client[:grid_id])
        Agent::NodePlugger.new(grid, node).plugin! if grid
      end
```

The `Grid.find_by(node_id: client[:grid_id])` is always going to be nil, so this case is broken, and it will never re-plug the node.

**Comment by SpComb** [comment] 2017-04-11 13:09
So this condition seems to be caused by a race between two different server worker `WebsocketBackend`s first plugging in the node on a websocket open, and then unpluggging the node on a websocket close. This race seems to be triggered when the agent's `WebsocketClient` considers the connection be closed and reconnects before the slow server worker's `WebsocketBackend` has processed the close of the original connection. If the new websocket connection goes to a different server worker, that faster `WebsocketBackend` might processes the connect event before the slower worker has processed the close event. That leaves the agent websocket connection active, but the server `HostNode` disconnected.

The logs actually contain two separate races that leave the agent disconnected... the first one is short-lived, as the agent itself decides to reconnect after a ping timeout. In the first case, the agent considers the websocket to be closed and reconnects, having the server process the connect event before the close event is processed. In the second case, it seems like the agent attempts to reconnect, but the websocket connection fails before it restarts itself. After restarting and connecting, the server seems to first pick up the failed reconnection attempt's connection event before the post-restart connection event, and then finally picks up the pre-restart close event?

Still not sure exactly how the agent and server websocket / eventmachine events behave with respect to the INFO-level server logs... sometimes the agent only gets the `on :close` after the server has processed and logged the `on :close`, other times the agent sees the `on :close` and reconnects well before the server has processed and logged the `on :close`?

A more detailed analysis of the logs follows... all logs are in approximate time order... the server and agent clocks appear to be fairly close, but I'm not sure if they're within 100ms or 10ms of eachother..? Based on the timing of the agent and server events, the server seems to be extremely slow, taking 14-40s to respond to things the agent does. The agent seems to respond to things the server does much faster, which would indicate that the slowness is happening inside the server's EventMachine threads, not the network.

Still need to figure out how to fix this for 1.2... first step is better diagnostics, which would include the new `WaitHelper` logging of slow RPCs and RPC timeouts. The agent `WebsocketClient` and server `WebsocketBackend` also need better logging... finally, #2139 would implement a watchdog for the server's EventMachine thread, logging stack traces and aborting if EM stalls, allowing the server worker to restart, and giving much better diagnostics.

---

The agent has a WebSocket connection open, and the server is alive, but it's too slow to respond to the agent's keepalive pings, so the agent `WebsocketClient` decides to close the websocket...

```
 I, [2017-03-27T00:49:36.268170 #1]  INFO -- Kontena::WebsocketClient: did not receive pong, closing connection
```

This takes ~14s until the server's `#7` worker processes the close frame and the socket gets closed:
```
I, [2017-03-27T00:49:50.520048 #7]  INFO -- WebsocketBackend: node closed connection: app3
```

This indicates that the websocket connection is alive, but it has an extremely high latency somewhere.

```
I, [2017-03-27T00:49:50.531774 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1000
```

In this case, the agent `WebsocketClient` seems to wait until the server has processed the close even before considering its websocket connection to be closed, and reconnecting.

The agent quickly reconnects, and this connection goes to the `#11` worker, which is fast to respond to the websocket open event (~500ms):

```
I, [2017-03-27T00:49:51.166881 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://master.example.com
I, [2017-03-27T00:49:51.642022 #1]  INFO -- Kontena::WebsocketClient: connection established
```
```
I, [2017-03-27T00:49:51.641696 #11]  INFO -- WebsocketBackend: node opened connection: app3, labels: [\"region=singlehop-chi\"]
```

In this case everything went well: the agent closed the connection, the server worker processed the close, the agent reconnected, and a different server worker processed the connect.

---

However, the agent isn't happy for long after reconnecting... ~15s later it times out its keepalive ping, so it starts to close the connection:
```
I, [2017-03-27T00:50:06.268568 #1]  INFO -- Kontena::WebsocketClient: did not receive pong, closing connection
```

This time, however, the agent seems to see the connection close after ~25s, but the server's `#11` worker has not yet seen the `on :close` event:

```
I, [2017-03-27T00:50:31.123263 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1000
```

So before the old connection's `WebsocketBackend` worker has processed on the `on :close`, the agent reconnects, which takes ~5s to see `on :open`:

```
I, [2017-03-27T00:50:31.338012 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://master.example.com
I, [2017-03-27T00:50:36.567695 #1]  INFO -- Kontena::WebsocketClient: connection established
```

The server's `#7` worker's `WebsocketBackend` picks up this connection at approximately the same time:

```
I, [2017-03-27T00:50:36.561808 #7]  INFO -- WebsocketBackend: node opened connection: app3, labels: [\"region=singlehop-chi\"]
```

And then ~3s later, the old `#11` worker's `WebsocketBackend` eventually processes the `on :close` event:

```
I, [2017-03-27T00:50:39.124765 #11]  INFO -- WebsocketBackend: node closed connection: app3
```

At this point the race has happened, and the agent has an active websocket connection open with the `#7` worker, but the `#11` worker has marked it as offline.

----

Some more bouncing follows, as the server is still too slow to respond to pings:

```
I, [2017-03-27T00:51:06.269115 #1]  INFO -- Kontena::WebsocketClient: did not receive pong, closing connection
I, [2017-03-27T00:51:08.462012 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1000
```

Again, the agent sees the websocket connection being closed before the server has processed it, and reconnects:

```
I, [2017-03-27T00:51:09.417564 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://master.example.com
```

This time, however, the server first processes the close event, ~25s after the agent considers it to be closed:

```
I, [2017-03-27T00:51:33.228205 #7]  INFO -- WebsocketBackend: node closed connection: app3
```

It seems like the new connection happaned to go to the same server worker, which then processes the websocket open event, ~3s after the open event, ~27s after the agent started connecting:

```
I, [2017-03-27T00:51:36.530151 #7]  INFO -- WebsocketBackend: node opened connection: app3, labels: [\"region=singlehop-chi\"]
```

The agent considers the connection to be opened at roughly the same time:

```
I, [2017-03-27T00:51:36.524576 #1]  INFO -- Kontena::WebsocketClient: connection established
```

This time the agent reconnect didn't race, presumably because both the old and new connections went to the same server worker process.

--- 

The agent isn't happy with that connection either, and the keepalive ping times out again. This time, the server is too slow to respond to the close for tha connection, so the agent abandons it:

```
I, [2017-03-27T00:52:06.269462 #1]  INFO -- Kontena::WebsocketClient: did not receive pong, closing connection
W, [2017-03-27T00:52:36.272074 #1]  WARN -- Kontena::WebsocketClient: Hit close timeout, abandoning existing websocket connection
I, [2017-03-27T00:52:36.272228 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
```

Then it still tries to reconnect once:

```
I, [2017-03-27T00:52:36.547458 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://master.example.com
I, [2017-03-27T00:52:44.578699 #1]  INFO -- Kontena::WebsocketClient: connection closed with code: 1006
```

The reconnect fails with the 1006 code, which indicates something like a connection refused (missing the improved WS error handling in #1757) error, so I wouldn't expect the server to even see this connect event?

---

Then the `kontena-agent` container is apparently restarted:

```
I, [2017-03-27T00:52:45.512839 #1]  INFO -- Kontena::WebsocketClient: initialized with token 3AurXapGG8M...
```

At this point the ordering of events becomes unclear, but I think the server sees the abandoned (?) connection getting closed, ~40s later:

```
I, [2017-03-27T00:52:46.177176 #7]  INFO -- WebsocketBackend: node closed connection: app3
```

Then the server's `#7` worker picks up a mystery websocket connection from somewhere... maybe it was the reconnect that failed with 1006 before the agent restarted? 

```
I, [2017-03-27T00:52:47.075842 #7]  INFO -- WebsocketBackend: node opened connection: app3, labels: [\"region=singlehop-chi\"]
```

This is the connection that ends up getting closed quickly, and causes the condition.

Then the final race happens, as the agent connects after restarting:

```
I, [2017-03-27T00:52:47.114314 #1]  INFO -- Kontena::WebsocketClient: connecting to master at wss://master.example.com
```

Not sure what the ordering between the agent and server here is... but it looks like the scauses the 
erver's `#11` worker picks up this connection:

```
I, [2017-03-27T00:52:47.480824 #11]  INFO -- WebsocketBackend: node opened connection: app3, labels: [\"region=singlehop-chi\"]
```

And the agent sees it as being connected:

```
I, [2017-03-27T00:52:47.491761 #1]  INFO -- Kontena::WebsocketClient: connection established
```

And finally the server's `#7` worker sees the mystery connection getting closed, which leaves the agent disconnected:

```
I, [2017-03-27T00:53:08.492946 #7]  INFO -- WebsocketBackend: node closed connection: app3
```

**Comment by SpComb** [comment] 2017-04-13 11:59
Kontena 1.2.0.rc1 and rc2 should fix the handling of websocket connections for disconnected nodes, including better logging of websocket events, as well as the EventMachine watchdog for better diagnostics of slow server EventMachine threads.

This should be enough to mitigate this issue for the 1.2.0 release. The agent websocket connections can still race, but the server will close any active websocket connection for a disconnected node, allowing the agent to reconnect, and hopefully not race again.

#2144 would then include a complete fix for this, having the agent send a `Kontena-Connected-At` timestamp to allow the sever to detect outdated websocket events, and refuse to plugin or unplug the node if it has a newer connection, avoiding the race condition.

**Comment by colinmollenhour** [comment] 2017-04-13 14:16
My main concern for 1.2 would be that if a node is disconnected from the master that the containers running on it remain intact both while disconnected and upon re-connection when nothing has changed with the service to warrant a container being destroyed. For example, when daemon strategy is used or HA strategy is used and scaling has not changed and another node has not already taken its place. Will this stability of existing containers be the case with 1.2.0?

**Comment by jakolehm** [comment] 2017-04-13 15:14
We changed stateful service behaviour between 1.2.0.rc1 -> rc2 back to old. So scheduler does not make any changes to service instances automatically, changes happens only when user issues a deploy command.

**Comment by jakolehm** [comment] 2017-04-13 15:16
Revert to old behaviour, see #2137

**Comment by colinmollenhour** [comment] 2017-04-13 15:36
Cool, thanks for clarifying!

**Comment by SpComb** [comment] 2017-04-19 11:42
Closing this issue in favor of #2183, which is specifically about the websocket open/close races.

With Kontena 1.2, the agent websocket connections can still race and mark the node as offline, but the agent should be able to reconnect and resolve the situation.

**Closed by SpComb** 2017-04-19 11:42 UTC
Labels: agent, server
