### ISSUE TITLE
Allow configuration for vagrant to use hyper-v instead of virtualbox

### ISSUE THREAD

**Issue by airtonix** [kontena/kontena#2665] opened 2017-08-07 02:30 UTC
I already have docker for windows which uses hyper-v.

**Comment by jnummelin** [comment] 2017-08-21 10:24
Duplicate of: https://github.com/kontena/kontena-plugin-vagrant/issues/36

Feel free to chime in on the other issue with requirements/comments.

**Closed by jnummelin** 2017-08-21 10:24 UTC
Labels: duplicate
