### ISSUE TITLE
container ls is returning NoMethodError

### ISSUE THREAD

**Issue by nevalla** [kontena/kontena#3330] opened 2018-03-15 06:28 UTC
When container does not have node info `kontena container ls` returns error:
```
$ kontena container ls
 [done] Retrieving container list     
 [error] NoMethodError : undefined method `[]' for nil:NilClass
         See /Users/lauri/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
```

In my case error was caused orphaned `kontena-agent` container.

**Comment by SpComb** [comment] 2018-03-15 08:37
This issue has several duplicates:  #2551  #1574

**Comment by SpComb** [comment] 2018-03-15 08:42
Closing as duplicate of #1574

**Closed by SpComb** 2018-03-15 08:42 UTC
Labels: bug, cli
