### ISSUE TITLE
kontena master dies sometimes on OpenSSL CipherErrors with Let's Encrypt cert

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1850] opened 2017-02-14 10:49 UTC
I've seen this happen ~5 times now. After this I delete mongo and start again (as initialadmincode is used)

```
Attaching to kontena_master_1
master_1   | [1] Puma starting in cluster mode...
master_1   | [1] * Version 3.6.0 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
master_1   | [1] * Min threads: 8, max threads: 8
master_1   | [1] * Environment: production
master_1   | [1] * Process workers: 1
master_1   | [1] * Phased restart available
master_1   | [1] * Listening on tcp://0.0.0.0:9292
master_1   | [1] Use Ctrl-C to stop
master_1   | [7] + Gemfile in context: /app/Gemfile
master_1   | I, [2017-02-14T10:37:06.462946 #7]  INFO -- ContainerCleanupJob: starting to cleanup stale containers
master_1   | I, [2017-02-14T10:37:06.465454 #7]  INFO -- DistributedLockCleanupJob: starting to cleanup stale locks
master_1   | I, [2017-02-14T10:37:06.465881 #7]  INFO -- MongoPubsub: starting to tail collection
master_1   | I, [2017-02-14T10:37:06.467690 #7]  INFO -- NodeCleanupJob: starting to cleanup stale connections
master_1   | I, [2017-02-14T10:37:06.468318 #7]  INFO -- NodeCleanupJob: starting to cleanup stale nodes
master_1   | I, [2017-02-14T10:37:06.469628 #7]  INFO -- ServiceBalancerJob: starting to watch services
master_1   | I, [2017-02-14T10:37:06.471066 #7]  INFO -- LeaderElectorJob: participating leader elections
master_1   | I, [2017-02-14T10:37:06.509166 #7]  INFO -- LeaderElectorJob: won election ♚
master_1   | [1] - Worker 0 (pid: 7) booted, phase: 0
master_1   | 185.11.211.158 - - [14/Feb/2017:10:40:19 +0000] "GET / HTTP/1.1" 200 78 0.0016
master_1   |
master_1   | OpenSSL::Cipher::CipherError (bad decrypt):
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/symmetric-encryption-3.8.2/lib/symmetric_encryption/cipher.rb:530:in `final'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/symmetric-encryption-3.8.2/lib/symmetric_encryption/cipher.rb:530:in `binary_decrypt'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/symmetric-encryption-3.8.2/lib/symmetric_encryption/symmetric_encryption.rb:121:in `decrypt'
master_1   |   /app/app/models/configuration.rb:37:in `decrypt'
master_1   |   /app/app/models/configuration.rb:59:in `get'
master_1   |   /app/app/models/configuration.rb:78:in `[]'
master_1   |   /app/app/helpers/digest_helper.rb:21:in `salt'
master_1   |   /app/app/helpers/digest_helper.rb:32:in `digest'
master_1   |   /app/app/helpers/digest_helper.rb:15:in `digest'
master_1   |   /app/app/models/access_token.rb:62:in `block in <class:AccessToken>'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:445:in `instance_exec'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:445:in `block in make_lambda'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:161:in `block in halting'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:501:in `block in call'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:501:in `each'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:501:in `call'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/activesupport-4.1.14/lib/active_support/callbacks.rb:86:in `run_callbacks'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/interceptable.rb:138:in `run_callbacks'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/persistable/creatable.rb:116:in `prepare_insert'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/persistable/creatable.rb:23:in `insert'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/persistable/creatable.rb:180:in `block in create!'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/threaded/lifecycle.rb:156:in `_creating'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/mongoid-4.0.2/lib/mongoid/persistable/creatable.rb:175:in `create!'
master_1   |   /app/app/models/access_token.rb:117:in `find_internal_by_code'
master_1   |   /app/app/routes/oauth2/token_api.rb:41:in `block (2 levels) in <class:TokenApi>'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:713:in `always'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:448:in `is'
master_1   |   /app/app/routes/oauth2/token_api.rb:29:in `block in <class:TokenApi>'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `instance_exec'
master_1   |   /usr/lib/ruby/gems/2.3.0/gems/roda-2.5.0/lib/roda.rb:250:in `block in call'
```

**Comment by SpComb** [comment] 2017-02-20 10:38
The stack trace is from the `SymmetricEncryption` cipher used for the Kontena vault and configuration, as related to the `VAULT_KEY/IV` envs. The LE SSL cert used by `kontena-server-haproxy` presumably isn't relevant.

**Comment by SpComb** [comment] 2017-06-30 06:19
Typically the `OpenSSL::Cipher::CipherError (bad decrypt)` would be caused by unexpected changes to the server `VAULT_KEY` or `VAULT_IV` - the server will fail when decrypting the stored secrets using the wrong key/IV.

Closing because no hints at what might be wrong with the LE SSL cert - in a typically deployment the server never even touches the SSL cert, that gets configured via the separate `kontena/haproxy` container.

**Closed by SpComb** 2017-06-30 06:19 UTC
Labels: server
