### ISSUE TITLE
CLI: undefined method from running grid show or node ls

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1263] opened 2016-11-01 11:28 UTC
I have a script:

```
while true; do
  kontena grid show grid_name
  kontena node ls
  sleep 5
done;
```

this randomly spits out
```
 [error] undefined method `[]' for nil:NilClass
         Rerun the command with environment DEBUG=true set to get the full exception
```

with 0.15.x and 0.16.1

**Comment by jnummelin** [comment] 2016-12-19 13:54
@matti Can you still reproduce this? I've been running that loop for more than 5 minutes without any failures.
If you can still reproduce this, could you run it with `DEBUG=true` to see the stacktrace where it fails. Gives some clue why it might fail.

**Comment by jnummelin** [comment] 2017-01-19 18:17
I'll close this as "not able to reproduce". Let's re-open if needed.

**Closed by jnummelin** 2017-01-19 18:17 UTC
Labels: bug, cli
