### ISSUE TITLE
ERROR -- Kontena::NetworkAdapters::IpamCleaner: Docker::Error::NotFoundError: open /var/lib/docker/overlay/.../lower-id: no such file or directory

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1533] opened 2016-12-09 13:48 UTC
May be related to  #1526

```
kontena-agent | D, [2016-12-09T13:47:47.499604 #1] DEBUG -- NetworkAdapters::IpamCleaner: got index 22689 for IPAM cleanup. Waiting for pending deployments for 30 secs...
 

kontena-agent | D, [2016-12-09T13:48:17.503016 #1] DEBUG -- NetworkAdapters::IpamCleaner: starting to collect locally known addresses
kontena-agent | E, [2016-12-09T13:48:17.534839 #1] ERROR -- Kontena::NetworkAdapters::IpamCleaner: Docker::Error::NotFoundError: open /var/lib/docker/overlay/b3518e73c4c3b5ce7e60eab10c7b7343c8959a9c0337430a37fde1dd24455e0e/lower-id: no such file or directory
kontena-agent | 
kontena-agent | D, [2016-12-09T13:48:17.535112 #1] DEBUG -- NetworkAdapters::IpamCleaner: /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:46:in `rescue in request'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:38:in `request'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/docker-api-1.32.1/lib/docker/container.rb:153:in `block (2 levels) in <class:Container>'
kontena-agent | /app/lib/docker/container.rb:197:in `cached_json'
kontena-agent | /app/lib/docker/container.rb:14:in `labels'
kontena-agent | /app/lib/docker/container.rb:181:in `overlay_cidr'
kontena-agent | /app/lib/docker/container.rb:173:in `overlay_ip'
kontena-agent | /app/lib/kontena/network_adapters/ipam_cleaner.rb:51:in `block in collect_local_addresses'
kontena-agent | /app/lib/kontena/network_adapters/ipam_cleaner.rb:50:in `each'
kontena-agent | /app/lib/kontena/network_adapters/ipam_cleaner.rb:50:in `collect_local_addresses'
kontena-agent | /app/lib/kontena/network_adapters/ipam_cleaner.rb:42:in `cleanup_ipam'
kontena-agent | /app/lib/kontena/network_adapters/ipam_cleaner.rb:27:in `block in run'
kontena-agent | /app/lib/kontena/network_adapters/ipam_cleaner.rb:23:in `loop'
kontena-agent | /app/lib/kontena/network_adapters/ipam_cleaner.rb:23:in `run'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
kontena-agent | /usr/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by jnummelin** [comment] 2016-12-22 09:55
Most likely the cause was same as in #1526, so closing. Let's re-open if we see it after the fix.

**Closed by jnummelin** 2016-12-22 09:55 UTC
