### ISSUE TITLE
Can't install gem kontena-cli

### ISSUE THREAD

**Issue by bibendi** [kontena/kontena#824] opened 2016-06-30 09:07 UTC
```
$ sudo gem install kontena-cli
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: kontena-cli requires dry-logic (= 0.2.2); dry-validation requires dry-logic (>= 0.2.2, ~> 0.2); dry-types requires dry-logic (>= 0.2.3, ~> 0.2)
```

Why you are using very strong dependencies rules?

**Comment by bibendi** [comment] 2016-06-30 09:21
workaround:

```
$ gem install dry-types --version 0.7.1
$ gem install dry-logic --version 0.2.2
$ gem install kontena-cli
```

**Comment by nevalla** [comment] 2016-06-30 09:52
Thanks for reporting this issue. The problem is caused by dry-logic gem version. The reason for strong dependencies rules is that there are certain issues in `dry-validation` gem and it's dependencies. I hope they will release a new version soon where these issues will be fixed (changes are already in GitHub). Meanwhile I will fix Kontena CLI gem dependencies.

**Comment by kke** [comment] 2016-07-01 08:19
@bibendi Do you have any clues how you got into that situation? Did you install some dry-* gems before? We can't seem to reproduce this. Which ruby version are you using?

**Comment by bibendi** [comment] 2016-07-01 11:55
Mac os x with "standart native" ruby
$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
$ gem list | grep dry
$ gem list | grep kontena
$ sudo gem install kontena-cli
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: kontena-cli requires dry-logic (= 0.2.2); dry-validation requires dry-logic (>= 0.2.2, ~> 0.2); dry-types requires dry-logic (>= 0.3.0, ~> 0.3)

**Comment by kke** [comment] 2016-07-01 11:58
I discussed this with dry-devs and they are releasing a new version any minute now. We still need to update our gemspec to use the new version.

**Comment by bibendi** [comment] 2016-07-01 11:58
In latest ruby OK

$ docker run --rm -it ruby:2.3-slim bash
root@7f79bda0977d:/# gem install kontena-cli
Fetching: excon-0.49.0.gem (100%)
Successfully installed excon-0.49.0
Fetching: colorize-0.8.1.gem (100%)
Successfully installed colorize-0.8.1
Fetching: clamp-1.0.0.gem (100%)
Successfully installed clamp-1.0.0
Fetching: highline-1.7.8.gem (100%)
Successfully installed highline-1.7.8
Fetching: shell-spinner-1.0.4.gem (100%)
Successfully installed shell-spinner-1.0.4
Fetching: ruby_dig-0.0.2.gem (100%)
Successfully installed ruby_dig-0.0.2
Fetching: concurrent-ruby-1.0.2.gem (100%)
Successfully installed concurrent-ruby-1.0.2
Fetching: dry-configurable-0.1.6.gem (100%)
Successfully installed dry-configurable-0.1.6
Fetching: dry-container-0.3.4.gem (100%)
Successfully installed dry-container-0.3.4
Fetching: dry-equalizer-0.2.0.gem (100%)
Successfully installed dry-equalizer-0.2.0
Fetching: dry-logic-0.2.2.gem (100%)
Successfully installed dry-logic-0.2.2
Fetching: inflecto-0.0.2.gem (100%)
Successfully installed inflecto-0.0.2
Fetching: kleisli-0.2.7.gem (100%)
Successfully installed kleisli-0.2.7
Fetching: dry-types-0.7.1.gem (100%)
Successfully installed dry-types-0.7.1
Fetching: dry-validation-0.7.4.gem (100%)
Successfully installed dry-validation-0.7.4
Fetching: kontena-cli-0.14.3.gem (100%)
Successfully installed kontena-cli-0.14.3
16 gems installed

**Comment by nevalla** [comment] 2016-07-01 12:01
I tested this also with 2.0-slim docker image

```
Status: Downloaded newer image for ruby:2.0-slim
# ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-linux]
# gem install kontena-cli
Fetching: excon-0.49.0.gem (100%)
Successfully installed excon-0.49.0
Fetching: colorize-0.8.1.gem (100%)
Successfully installed colorize-0.8.1
Fetching: clamp-1.0.0.gem (100%)
Successfully installed clamp-1.0.0
Fetching: highline-1.7.8.gem (100%)
Successfully installed highline-1.7.8
Fetching: shell-spinner-1.0.4.gem (100%)
Successfully installed shell-spinner-1.0.4
Fetching: ruby_dig-0.0.2.gem (100%)
Successfully installed ruby_dig-0.0.2
Fetching: concurrent-ruby-1.0.2.gem (100%)
Successfully installed concurrent-ruby-1.0.2
Fetching: dry-configurable-0.1.6.gem (100%)
Successfully installed dry-configurable-0.1.6
Fetching: dry-container-0.3.4.gem (100%)
Successfully installed dry-container-0.3.4
Fetching: dry-equalizer-0.2.0.gem (100%)
Successfully installed dry-equalizer-0.2.0
Fetching: dry-logic-0.2.2.gem (100%)
Successfully installed dry-logic-0.2.2
Fetching: inflecto-0.0.2.gem (100%)
Successfully installed inflecto-0.0.2
Fetching: kleisli-0.2.7.gem (100%)
Successfully installed kleisli-0.2.7
Fetching: dry-types-0.7.1.gem (100%)
Successfully installed dry-types-0.7.1
Fetching: dry-validation-0.7.4.gem (100%)
Successfully installed dry-validation-0.7.4
Fetching: kontena-cli-0.14.3.gem (100%)
Successfully installed kontena-cli-0.14.3
16 gems installed
```

**Comment by solnic** [comment] 2016-07-01 12:10
This should be fixed once you merge in https://github.com/kontena/kontena/pull/831

**Closed** 2016-07-01 18:36 UTC
Labels: bug, cli
