### ISSUE TITLE
Containers missing in weave network

### ISSUE THREAD

**Issue by mtrofimm** [kontena/kontena#1285] opened 2016-11-04 09:49 UTC
I have a app with 4 services. All of them are started and running. The list of the containers attached to weave network shows only 2 of them: (weave ps)
```
weave:expose b2:c8:97:75:91:eb 10.81.0.5/19
2f30230ff690 22:74:a0:c9:96:bd 10.81.1.107/19
c60001026df2 76:39:f0:6c:65:b4 10.81.1.104/19
```

The result of weave status dns is OK: (there are entries for all 4 containers)
```
xxxxxxxxx-pl-www-procunfintrans-1.xxxxxxxxxpl 10.81.1.108     191b5c43d02e b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-procunfintrans-1 10.81.1.108     191b5c43d02e b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-procunfintrans.xxxxxxxxxpl 10.81.1.108     191b5c43d02e b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-procunfintrans 10.81.1.108     191b5c43d02e b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-reportgenerate-1.xxxxxxxxxpl 10.81.1.107     2f30230ff690 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-reportgenerate-1 10.81.1.107     2f30230ff690 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-reportgenerate.xxxxxxxxxpl 10.81.1.107     2f30230ff690 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-reportgenerate 10.81.1.107     2f30230ff690 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-web-1.xxxxxxxxxpl 10.81.1.104     c60001026df2 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-web-1 10.81.1.104     c60001026df2 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-web.xxxxxxxxxpl 10.81.1.104     c60001026df2 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-web 10.81.1.104     c60001026df2 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-zzzredir-www-1.xxxxxxxxxpl 10.81.1.106     57dafb559169 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-zzzredir-www-1 10.81.1.106     57dafb559169 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-zzzredir-www.xxxxxxxxxpl 10.81.1.106     57dafb559169 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-zzzredir-www 10.81.1.106     57dafb559169 b2:c8:97:75:91:eb
```

weave:1.7.2
agent: 0.16.0
docker: 1.11.2
os: coreos@digitalocean

**Comment by jakolehm** [comment] 2016-11-04 10:55
Does restarting a container enable weave address?

**Comment by mtrofimm** [comment] 2016-11-04 11:10
I tried restarting and creating app's containers without success.
Weave container Logs from container restart:
```
INFO: 2016/11/04 11:05:38.194609 [nameserver b2:c8:97:75:91:eb] container 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48 died; tombstoning entry xxxxxxxxx-pl-www-zzzredir-www-1.xxxxxxxxxpl.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.194751 [nameserver b2:c8:97:75:91:eb] container 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48 died; tombstoning entry xxxxxxxxx-pl-www-zzzredir-www-1.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.194778 [nameserver b2:c8:97:75:91:eb] container 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48 died; tombstoning entry xxxxxxxxx-pl-www-zzzredir-www.xxxxxxxxxpl.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.194800 [nameserver b2:c8:97:75:91:eb] container 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48 died; tombstoning entry xxxxxxxxx-pl-www-zzzredir-www.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.805738 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www-1.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.867783 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.891680 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www-1.xxxxxxxxxpl.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.918470 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www.xxxxxxxxxpl.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:40.025836 Discovered local MAC 0a:b1:c8:7f:81:ca
INFO: 2016/11/04 11:05:40.174841 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www-1.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:54.030224 Discovered local MAC 6e:63:64:11:13:8a
```
There is one more issue with weave. I downloaded weave binary and saved in /tmp
```
$ /tmp/weave status ipam  
error during template execution
```
in the weave container logs there is:
```
ERRO: 2016/11/04 11:06:12.621058 template: ipamTemplate:1:26: executing "ipamTemplate" at <.IPAM>: dereference of nil pointer of type ipam.Status
```
I'm not sure if it's related.

**Comment by jakolehm** [comment] 2016-11-04 11:11
Ipam error is not related (Kontena is not using Weave ipam). How about if you restart kontena-agent container?

**Comment by SpComb** [comment] 2016-11-04 11:17
Are the Docker service containers running, but stuck in the `/w/w` entrypoint? Use `docker exec service-1 ip addr` to check for the presence of the `ethwe` interface.

>  agent: 0.16.0

Kontena 0.16.0 has startup issues with weave after a reboot, try upgrading to 0.16.1, 0.16.2.

> The list of the containers attached to weave network shows only 2 of them: (weave ps)
> 
>> weave:expose b2:c8:97:75:91:eb 10.81.0.5/19
>> 2f30230ff690 22:74:a0:c9:96:bd 10.81.1.107/19
>> c60001026df2 76:39:f0:6c:65:b4 10.81.1.104/19

`weave ps` only shows local containers, not remote containers running on other nodes, so the expected output of `weave ps` depends on the number of nodes that you are running.

**Comment by mtrofimm** [comment] 2016-11-04 11:24
kontena-agent restart no chnage. weave logs:
```
INFO: 2016/11/04 11:05:38.194609 [nameserver b2:c8:97:75:91:eb] container 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48 died; tombstoning entry xxxxxxxxx-pl-www-zzzredir-www-1.xxxxxxxxxpl.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.194751 [nameserver b2:c8:97:75:91:eb] container 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48 died; tombstoning entry xxxxxxxxx-pl-www-zzzredir-www-1.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.194778 [nameserver b2:c8:97:75:91:eb] container 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48 died; tombstoning entry xxxxxxxxx-pl-www-zzzredir-www.xxxxxxxxxpl.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.194800 [nameserver b2:c8:97:75:91:eb] container 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48 died; tombstoning entry xxxxxxxxx-pl-www-zzzredir-www.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.805738 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www-1.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.867783 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.891680 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www-1.xxxxxxxxxpl.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:38.918470 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www.xxxxxxxxxpl.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:40.025836 Discovered local MAC 0a:b1:c8:7f:81:ca
INFO: 2016/11/04 11:05:40.174841 [nameserver b2:c8:97:75:91:eb] adding entry for 57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48: xxxxxxxxx-pl-www-zzzredir-www-1.kontena.local. -> 10.81.1.106
INFO: 2016/11/04 11:05:54.030224 Discovered local MAC 6e:63:64:11:13:8a
```
weave ps - no change

all 4 containers are running on the same host. 
2 missing containers have ethwe interface
```
$ docker exec -it xxxxxx-pl-www-procunfintrans-1 ip a |grep ethwe
197: ethwe@if198: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default 
    inet 10.81.1.108/19 scope global ethwe
```
```
$ docker exec -it xxxxx-pl-www-zzzredir-www-1 ip a |grep ethwe                                                                                                                                 
201: ethwe@if202: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default 
    inet 10.81.1.106/19 scope global ethwe
```
```
weave status dns: 
xxxxxxxxx-pl-www-procunfintrans-1.xxxxxxxxxpl 10.81.1.108     191b5c43d02e b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-procunfintrans-1 10.81.1.108     191b5c43d02e b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-procunfintrans.xxxxxxxxxpl 10.81.1.108     191b5c43d02e b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-procunfintrans 10.81.1.108     191b5c43d02e b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-reportgenerate-1.xxxxxxxxxpl 10.81.1.107     2f30230ff690 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-reportgenerate-1 10.81.1.107     2f30230ff690 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-reportgenerate.xxxxxxxxxpl 10.81.1.107     2f30230ff690 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-reportgenerate 10.81.1.107     2f30230ff690 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-web-1.xxxxxxxxxpl 10.81.1.104     c60001026df2 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-web-1 10.81.1.104     c60001026df2 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-web.xxxxxxxxxpl 10.81.1.104     c60001026df2 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-web 10.81.1.104     c60001026df2 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-zzzredir-www-1.xxxxxxxxxpl 10.81.1.106     57dafb559169 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-zzzredir-www-1 10.81.1.106     57dafb559169 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-zzzredir-www.xxxxxxxxxpl 10.81.1.106     57dafb559169 b2:c8:97:75:91:eb
xxxxxxxxx-pl-www-zzzredir-www 10.81.1.106     57dafb559169 b2:c8:97:75:91:eb
```
```
weave ps
weave:expose b2:c8:97:75:91:eb 10.81.0.5/19
2f30230ff690 22:74:a0:c9:96:bd 10.81.1.107/19
c60001026df2 76:39:f0:6c:65:b4 10.81.1.104/19
```

10.81.1.106 and 10.81.1.108 are missing here

**Comment by mtrofimm** [comment] 2016-11-04 11:30
1. docker rm -v -f kontena-agent weave weavedb kontena-etcd kontena-etcd-data kontena-cadvisor weavewait-1.7.2
2. sudo systemctl restart kontena-agent 
```
e060cbca6677        kontena/etcd:2.3.7                                        "/usr/bin/etcd --name"   2 minutes ago       Up 2 minutes                            kontena-etcd
a79f9f0089cf        weaveworks/weave:1.7.2                                    "/home/weave/weaver -"   2 minutes ago       Up 2 minutes                            weave
ea7262b682a5        kontena/cadvisor:0.23.2                                   "/entrypoint.sh --doc"   2 minutes ago       Up 2 minutes                            kontena-cadvisor
dc5bab7e9ba2        kontena/agent:0.16.2                                      "/app/bin/kontena-age"   2 minutes ago       Up 2 minutes                            kontena-agent
```
3. restart all app containers
4. weave ps
```
weave:expose b2:c8:97:75:91:eb 10.81.0.5/19
191b5c43d02e 72:c9:45:dd:6b:17 10.81.1.108/19
```

**Comment by mtrofimm** [comment] 2016-11-04 11:32
kontena app rm 
kontena app deploy
weave ps
weave:expose b2:c8:97:75:91:eb 10.81.0.5/19
577a41a0b685 ee:56:6f:17:e4:83 10.81.1.103/19

**Comment by jakolehm** [comment] 2016-11-04 11:41
Does this grid have any other nodes?

**Comment by mtrofimm** [comment] 2016-11-04 11:47
yes, kontena node list
```
xxxxxxxxx-utils2                                                          online     yes        region=fra1,usage=utils                 
xxxxxxxxx-mongo                                                           online     yes        region=fra1,usage=mongo                 
xxxxxxxxx-mysql                                                           online     yes        region=fra1,usage=mysql                 
lb01                                                                   online     no         region=fra1,usage=lb                    
xxxxxxxxx-worker01                                                        online     no         region=fra1,usage=web                  ```

weave status connections (at xxxxxxxxx-worker01)
```
-> 46.101.128.xxx:6783   established encrypted   sleeve 5a:dd:5f:e5:cf:93(xxxxxxxxx-mysql)
<- 139.59.136.xxx:57569  established encrypted   sleeve 2e:8e:5d:b7:7e:0c(www.xxxxxxxxx.pl)
-> 46.101.151.xx:6783    established encrypted   sleeve 32:43:30:16:43:5c(xxxxxxxxx-utils2)
<- 46.101.192.xxx:37477  established encrypted   sleeve 62:ab:0e:f3:6b:d9(xxxxxxxxx-mongo)
```

**Comment by jakolehm** [comment] 2016-11-04 11:48
I presume that this problem is only in one of those nodes (others work as expected)?

**Comment by SpComb** [comment] 2016-11-04 11:49
> 2 missing containers have ethwe interface
> 
> $ docker exec -it xxxxxx-pl-www-procunfintrans-1 ip a |grep ethwe
> 197: ethwe@if198: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default 
>     inet 10.81.1.108/19 scope global ethwe
> 
> $ docker exec -it xxxxx-pl-www-zzzredir-www-1 ip a |grep ethwe                                                                                                                                 
> 201: ethwe@if202: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default 
>     inet 10.81.1.106/19 scope global ethwe

So all four service containers have an ethwe interface, but `weave ps` only knows about some of them? Does traffic get forwarded between the containers, i.e. can you ping all four `10.81.1.X` service containers?

Does `docker ps -a` list any containers in the "Dead" state (`docker ps -a -f status=dead`), in particular, any `weaveexec` containers?

**Comment by mtrofimm** [comment] 2016-11-04 12:00
docker ps -a -f status=dead --> empty 
```
$ docker exec xxxxxxxxx-pl-www-zzzredir-www-1 ip a |grep ethwe
226: ethwe@if227: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default 
    inet 10.81.1.101/19 scope global ethwe

$ weave ps |grep 10.81.1.101
(empty)

$ weave ps |grep 10.81.1.100                                                                                                                                                               
684b342ff6c9 ca:1b:da:bd:fc:a2 10.81.1.100/19

$ docker exec -it xxxxxxxxx-pl-www-web-1 ip a |grep ethwe
238: ethwe@if239: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default 
    inet 10.81.1.100/19 scope global ethwe


docker exec -it xxxxxxxxx-pl-www-web-1 ping 10.81.1.101
PING 10.81.1.101 (10.81.1.101) 56(84) bytes of data.
From 10.81.1.100 icmp_seq=1 Destination Host Unreachable
From 10.81.1.100 icmp_seq=2 Destination Host Unreachable
```

**Comment by mtrofimm** [comment] 2016-11-04 12:08
one more strange issue in weave report container xxxxxxxxx-pl-www-zzzredir-www-1  has the following dns entries:
```
           {
                "Hostname": "xxxxxxxxx-pl-www-zzzredir-www-1.xxxxxxxxxpl.kontena.local.",
                "Origin": "b2:c8:97:75:91:eb",
                "ContainerID": "57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48",
                "Address": "10.81.1.106",
                "Version": 3,
                "Tombstone": 1478259037
            },
            {
                "Hostname": "xxxxxxxxx-pl-www-zzzredir-www-1.xxxxxxxxxpl.kontena.local.",
                "Origin": "b2:c8:97:75:91:eb",
                "ContainerID": "7ce60909410e68552d847b63b03faf3fa7eef3cd579c88189544b3a0332b4461",
                "Address": "10.81.1.101",
                "Version": 0,
                "Tombstone": 0
            },
            {
                "Hostname": "xxxxxxxxx-pl-www-zzzredir-www-1.kontena.local.",
                "Origin": "b2:c8:97:75:91:eb",
                "ContainerID": "57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48",
                "Address": "10.81.1.106",
                "Version": 3,
                "Tombstone": 1478259037
            },
            {
                "Hostname": "xxxxxxxxx-pl-www-zzzredir-www-1.kontena.local.",
                "Origin": "b2:c8:97:75:91:eb",
                "ContainerID": "7ce60909410e68552d847b63b03faf3fa7eef3cd579c88189544b3a0332b4461",
                "Address": "10.81.1.101",
                "Version": 0,
                "Tombstone": 0
            },
            {
                "Hostname": "xxxxxxxxx-pl-www-zzzredir-www.xxxxxxxxxpl.kontena.local.",
                "Origin": "b2:c8:97:75:91:eb",
                "ContainerID": "57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48",
                "Address": "10.81.1.106",
                "Version": 3,
                "Tombstone": 1478259037
            },
            {
                "Hostname": "xxxxxxxxx-pl-www-zzzredir-www.xxxxxxxxxpl.kontena.local.",
                "Origin": "b2:c8:97:75:91:eb",
                "ContainerID": "7ce60909410e68552d847b63b03faf3fa7eef3cd579c88189544b3a0332b4461",
                "Address": "10.81.1.101",
                "Version": 0,
                "Tombstone": 0
            },
            {
                "Hostname": "xxxxxxxxx-pl-www-zzzredir-www.kontena.local.",
                "Origin": "b2:c8:97:75:91:eb",
                "ContainerID": "57dafb559169775fe12a87d150f3c81444f3d0bddae9aa7d69ae123554b10c48",
                "Address": "10.81.1.106",
                "Version": 3,
                "Tombstone": 1478259037
            },
            {
                "Hostname": "xxxxxxxxx-pl-www-zzzredir-www.kontena.local.",
                "Origin": "b2:c8:97:75:91:eb",
                "ContainerID": "7ce60909410e68552d847b63b03faf3fa7eef3cd579c88189544b3a0332b4461",
                "Address": "10.81.1.101",
                "Version": 0,
                "Tombstone": 0
            },

```

with 10.81.1.101 and 10.81.1.106 addresses. Its ethwe interfaces has 10.81.1.101/19.

**Comment by SpComb** [comment] 2016-11-04 12:11
> one more strange issue in weave report container xxxxxxxxx-pl-www-zzzredir-www-1 has the following dns entries:

The `10.81.1.106` entries have a nonzero tombstone, so that in itself shouldn't be an issue, unless `getent hosts xxxxxxxxx-pl-www-zzzredir-www` also returns both `10.81.1.101` and `10.81.1.106`?

**Comment by mtrofimm** [comment] 2016-11-04 12:23
what do you mean by 'getent hosts'?
```
$ weave  dns-lookup xxxxxxxxx-pl-www-web-1         
10.81.1.100
$ weave  dns-lookup xxxxxxxxx-pl-www-zzzredir-www-1
10.81.1.101
```

**Comment by SpComb** [comment] 2016-11-04 12:54
> $ docker exec xxxxxxxxx-pl-www-zzzredir-www-1 ip a |grep ethwe
> 226: ethwe@if227: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP group default 
>     inet 10.81.1.101/19 scope global ethwe
> 
> $ weave ps |grep 10.81.1.101
> (empty)

> $ docker exec -it xxxxxxxxx-pl-www-web-1 ip a |grep ethwe
> 238: ethwe@if239: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP > group default 
>     inet 10.81.1.100/19 scope global ethwe
> $ docker exec -it xxxxxxxxx-pl-www-web-1 ping 10.81.1.101
> PING 10.81.1.101 (10.81.1.101) 56(84) bytes of data.
> From 10.81.1.100 icmp_seq=1 Destination Host Unreachable
> From 10.81.1.100 icmp_seq=2 Destination Host Unreachable

It seems like the `weave attach` on the xxxxxxxxx-pl-www-zzzredir-www-1 container must have failed halfway-through to create the `ethwe` interface but not fully configure it.

Does `ip link show type veth | grep vethwe | grep -v master` on the host node show any `vethwepl*` interfaces that are not attached to the `weave` bridge? A normal weave veth should look like this on the host node (note the `master weave` part):

```
32: vethwepl4620@if31: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue master weave state UP mode DEFAULT group default 
```

You can try re-attaching the container manually, using `weave attach 10.81.1.101/19 xxxxxxxxx-pl-www-zzzredir-www-1`, and see if you get some error back, or if the `ping 10.81.1.101` starts working again.

Unfortunately the kontena-agent is still missing the weaveexec error logging (#1286) that would make these kind of weave errors easier to diagnose.

**Comment by mtrofimm** [comment] 2016-11-04 12:59
$ ip link show type veth | grep vethwe | grep -v master
227: vethwepl4840@if226: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP mode DEFAULT group default 
247: vethwepl7952@if246: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue state UP mode DEFAULT group default

**Comment by mtrofimm** [comment] 2016-11-04 13:02
```
$ weave attach 10.81.1.101/19 xxxxxx-pl-www-zzzredir-www-1                                                                                                                                 
10.81.1.101

$ weave ps                                                                                                                                                                                 
weave:expose b2:c8:97:75:91:eb 10.81.0.5/19
577a41a0b685 de:0a:ce:28:9e:1d 10.81.1.103/19
684b342ff6c9 ca:1b:da:bd:fc:a2 10.81.1.100/19
```
logs z weave container
```
INFO: 2016/11/04 13:00:43.699006 [nameserver b2:c8:97:75:91:eb] adding entry for 7ce60909410e68552d847b63b03faf3fa7eef3cd579c88189544b3a0332b4461: xxxxx-pl-www-zzzredir-www-1.kontena.local. -> 10.81.1.101
```

**Comment by mtrofimm** [comment] 2016-11-04 13:05
```
$ brctl show
bridge name     bridge id               STP enabled     interfaces
docker0         8000.024298958bea       no              veth3d892f3
                                                        veth5637718
                                                        veth64f301e
                                                        vethd95ec38
weave           8000.b2c8977591eb       no              vethwe-bridge
                                                        vethwepl6779
                                                        vethwepl7418
```

**Comment by SpComb** [comment] 2016-11-04 13:18
Okay, we're on the right track now, those host-side `vethwepl*` interfaces are missing from the weave bridge.

If you just want a quick hotfix, then try:

`ip link set  vethwepl4840 master weave`
`ip link set vethwepl7952 master weave` 

and I think the containers will start working.

For a real fix we need to know how and why the `weave attach ...` originally failed... You can try this hotpatch for 0.16.2 if you're feeling adventurous:

`systemctl stop kontena-agent`
`docker exec kontena-agent patch -p2 < kontena-agent_fix_weaveexec-error-logging.patch`
`docker start kontena-agent`

It should start logging any failed weaveexec commands.

Do a `systemctl restart kontena-agent` to rollback to the vanilla code.

#### `kontena-agent_fix_weaveexec-error-logging.patch`
```
diff --git a/agent/lib/kontena/network_adapters/weave.rb b/agent/lib/kontena/network_adapters/weave.rb
index 8f43c84..774de49 100644
--- a/agent/lib/kontena/network_adapters/weave.rb
+++ b/agent/lib/kontena/network_adapters/weave.rb
@@ -133,7 +133,8 @@ module Kontena::NetworkAdapters
           },
           'Env' => [
             'HOST_ROOT=/host',
-            "VERSION=#{WEAVE_VERSION}"
+            "VERSION=#{WEAVE_VERSION}",
+            "WEAVE_DEBUG=#{ENV['WEAVE_DEBUG']}",
           ],
           'HostConfig' => {
             'Privileged' => true,
@@ -161,6 +162,13 @@ module Kontena::NetworkAdapters
           error exc.message
           return false
         end
+
+        if (status_code = response["StatusCode"]) == 0
+          debug "weaveexec ok: #{cmd}"
+        else
+          logs = container.streaming_logs(stdout: true, stderr: true)
+          error "weaveexec exit #{status_code}: #{cmd}\n#{logs}"
+        end
         response
       ensure
         container.delete(force: true, v: true) if container
```

**Comment by mtrofimm** [comment] 2016-11-04 13:31
It's a testing site. I'm not such adventurous now :(

I set WEAVE_DEBUG=1 env variable for weave attach.
There are such entries:
It's a testing site. I'm not such adventurous now :(

I set WEAVE_DEBUG=1 env variable for weave attach. 
[debug.txt](https://github.com/kontena/kontena/files/571601/debug.txt)

after ip link set commands `weave ps` shows all containers.

**Comment by jakolehm** [comment] 2016-11-04 13:33
@SpComb just realized that this is in DO. Can this be somehow related to systemd/ipv6 thing that we have seen?

**Comment by SpComb** [comment] 2016-11-07 08:22
@mtrofimm What CoreOS version are you running when this happens?

I'm thinking it could well be explained by a Weave/systemd-networkd race on the veth interfaces:
https://github.com/coreos/bugs/issues/1554

Unfortunately the above fix in CoreOS is for Docker/libnetwork, not Weave.

**Comment by mtrofimm** [comment] 2016-11-07 09:37
@SpComb 
```
$ cat /etc/os-release  
NAME=CoreOS
ID=coreos
VERSION=1185.3.0
VERSION_ID=1185.3.0
BUILD_ID=2016-11-01-0605
PRETTY_NAME="CoreOS 1185.3.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
```
$ cat /etc/coreos/update.conf 
GROUP=stable
```

**Comment by bboreham** [comment] 2016-11-07 17:37
Hi, I'm from Weaveworks.  I have seen similar symptoms on a CoreOS machine; managed to jury-rig a work-around by overriding the config in `/usr/lib/systemd/network`

Since the issue seems to stem from systemd-networkd trying to manage the interface settings, we need to arrange that there is no network config that matches Weave's virtual ethernet devices.  So I copied `/usr/lib/systemd/network/zz-default.network` to `/etc/systemd/network/zz-default.network` and edited to add a `[Match]` section matching just physical interfaces, e.g.

    [Match]
    Name=eth*
 
I also had to blank out the Docker-veth file, via `touch /etc/systemd/network/50-docker-veth.network`. Since that file doesn't specify any behaviour, I think it's a similar attempt to avoid having systemd-networkd manage it.

These files under `/etc/systemd/network/` override the files with the same name in `/usr/lib/systemd/network`

Then `systemctl restart systemd-networkd` to have it re-read the config and Weave Net works again.

Unfortunately the content you want in the `zz-default` file will vary depending on what interfaces you want to have managed by systemd-networkd: the file format doesn't support negation of matches on Name or Driver which would make this easier.

**Comment by SpComb** [comment] 2016-11-07 17:57
Reference #1264 for the CoreOS systemd-networkd configuration on host nodes.

**Comment by colinmollenhour** [comment] 2016-11-08 20:36
I'm having issues where nodes can no longer connect to each other that sound similar to @mtrofimm's issues. I'd like to try to troubleshoot but can't figure out where the `weave` executable is located.. Can someone point me in the right direction?

In my case I'm testing with 4 nodes: 3 redis instances, 4 redis-sentinel instances and 4 haproxy instances. Some of the haproxy instances get timeouts or connection failures to some of the redis instances but some are able to connect to the instances that fail. Confirmed that it is not a redis or haproxy issue by using telnet successfully from one node but not another.. Would provide some debug info but can't find weave executable.. :)

**Comment by SpComb** [comment] 2016-11-08 21:13
The diagnostic for this issue is the presence of un-mastered veths, i.e. any output from `ip link show type veth | grep vethwe | grep -v master`.

> Does `ip link show type veth | grep vethwe | grep -v master` on the host node show any `vethwepl*` interfaces that are not attached to the `weave` bridge? A normal weave veth should look like this on the host node (note the `master weave` part):
> 
> `32: vethwepl4620@if31: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1410 qdisc noqueue master weave state UP mode DEFAULT group default`

The fix is to override the `systemd.network` units to not match the `vethwe` interfaces.

**Comment by mtrofimm** [comment] 2016-11-08 23:05
@colinmollenhour 
as for weave exec, I just downloaded it by `$ curl -L git.io/weave -o /tmp/weave`. 
I noticed that there is one more workaround. When I redeploy services one by one then it's fine. Problem occurs when I try to (re)deploy the whole app consisting of many services by `kontena app deploy`.

I have not tested @bboreham's solution yet.

**Comment by mudspot** [comment] 2016-11-09 05:32
Hi all,

I'm happy to report @bboreham works perfectly.

Terry

**Comment by SpComb** [comment] 2016-11-09 09:05
> So I copied /usr/lib/systemd/network/zz-default.network to /etc/systemd/network/zz-default.network and edited to add a [Match] section matching just physical interfaces, e.g.

This needs careful reading, don't just create a new `/etc/systemd/network/zz-default.network` file that has the `[Match]` section and nothing else, you need to add the `[Match]` section to the existing config, thus resulting in something like this:

```
[Match]
Name=eth*

[Network]
DHCP=yes

[DHCP]
UseMTU=true
UseDomains=true
```

Edited my earlier comment over in #1264 to give the correct example: https://github.com/kontena/kontena/issues/1264#issuecomment-258916553

**Comment by colinmollenhour** [comment] 2016-11-09 18:26
Just an FYI I am on Ubuntu 16.04, not CoreOS. I have upgraded everything to 0.16.2 and then completely rebooted every machine and haven't had the issue return so far but I will report back if I do. Thanks!

**Comment by SpComb** [comment] 2016-11-09 18:27
> Just an FYI I am on Ubuntu 16.04, not CoreOS

Are you using systemd-networkd, or the traditional Ubuntu ifupdown `/etc/network/interfaces`?

**Comment by colinmollenhour** [comment] 2016-11-09 19:05
I don't think systemd is being used but it is whatever the default networking is on packet.net for Ubuntu 16.04. Both /usr/lib/systemd/network/ and /etc/systemd/network/ are empty directories and I don't see any systemd files related to networking and /etc/network/interfaces is populated with the interfaces used by the system.

Currently there aren't any un-mastered veth interfaces based on your test command but I'll definitely check if I have the problem pop up again.

Thanks!

**Comment by SpComb** [comment] 2016-11-15 09:26
We were able to reproduce the issue with masterless `vethwe` interfaces on DigitalOcean with CoreOS 1185.3.0, and confirm that the systemd-networkd configuration fixes the issue.

Closing this in favor of https://github.com/kontena/kontena/issues/1264 to track the systemd-networkd configuration workaround within Kontena, and https://github.com/weaveworks/weave/issues/2601 to track any fixes to the issue within Weave.

**Closed by SpComb** 2016-11-15 09:26 UTC
Labels: agent
