### ISSUE TITLE
kontena vagrant master create does not work

### ISSUE THREAD

**Issue by stvndall** [kontena/kontena#2413] opened 2017-06-04 08:08 UTC
Trying to get the master up and running on my machine (following the get started guide)
With vagrant and virtual box. I have found that the vagrant plugin does not handle errors. And will rather spin indefinitely. I had to use debug mode to find the issues with my virtual box.

Not that I can finally get the vm attached, and running. The inline script appears to be broken, and never returns. I cannot find a debug switch for this.

```
 kontena vagrant master create -D
 _               _
| | _____  _ __ | |_ ___ _ __   __ _
| |/ / _ \| '_ \| __/ _ \ '_ \ / _` |
|   < (_) | | | | ||  __/ | | | (_| |
|_|\_\___/|_| |_|\__\___|_| |_|\__,_|
-------------------------------------
Kontena CLI (c) 2017 Kontena, Inc.
D, [2017-06-03T22:31:21.249045 #12686] DEBUG -- CONFIG: Loading configuration from /home/steven/.kontena_client.json
D, [2017-06-03T22:31:21.249240 #12686] DEBUG -- CONFIG: Configuration loaded with 0 servers.
D, [2017-06-03T22:31:21.249258 #12686] DEBUG -- CONFIG: Current master: (not selected)
D, [2017-06-03T22:31:21.249270 #12686] DEBUG -- CONFIG: Current grid: (not selected)
> Enter a name for this Kontena Master:  home
> Select OAuth2 authentication provider:  Kontena Cloud (recommended)
D, [2017-06-03T22:31:27.551019 #12686] DEBUG -- CLIENT: Excon opts: {:omit_default_port=>true, :connect_timeout=>5, :read_timeout=>30, :write_timeout=>5, :ssl_verify_peer=>true, :instrumentor=>Kontena::DebugInstrumentor}
D, [2017-06-03T22:31:27.551482 #12686] DEBUG -- CLIENT: Requesting user info from https://cloud-api.kontena.io/user
[API Client Request]: GET https://cloud-api.kontena.io/user (ssl_verify: true)  | Headers: {Accept: application/json, Authorization: Bearer} 
[API Client Response]: Headers: {Content-Type: application/json; charset=utf-8}  | Status: 200 | Body: "{\"data\":{\"type\":\"users\",\"id\":\"8c7def79-69dc-418b-9d94-ac3f687ecfff\",\..."
> Choose a size 2048MB
Bringing machine 'home' up with 'virtualbox' provider...
==> home: Importing base box 'coreos-stable'...
==> home: Matching MAC address for NAT networking...
==> home: Checking if box 'coreos-stable' is up to date...
==> home: Setting the name of the VM: home 
==> home: Clearing any previously set network interfaces...
==> home: Preparing network interfaces based on configuration...
    home: Adapter 1: nat
    home: Adapter 2: hostonly
==> home: Forwarding ports...
    home: 22 (guest) => 2222 (host) (adapter 1)
==> home: Running 'pre-boot' VM customizations...
==> home: Booting VM...                    
==> home: Waiting for machine to boot. This may take a few minutes...
    home: SSH address: 127.0.0.1:2222      
    home: SSH username: core
    home: SSH auth method: private key
==> home: Machine booted and ready!        
==> home: Setting hostname...
==> home: Configuring and enabling network interfaces...
==> home: Running provisioner: file...     
==> home: Running provisioner: shell...    
 [done] Creating Vagrant machine home      
    home: Running: inline script
```

after trying all sizes, I decided to leave it running all night in case.
```
 [fail] Waiting for home to start      ^C
Interrupt : 
/home/steven/.kontena/gems/2.3.1/gems/kontena-plugin-vagrant-0.2.7/lib/kontena/machine/vagrant/master_provisioner.rb:66:in `sleep'
  /home/steven/.kontena/gems/2.3.1/gems/kontena-plugin-vagrant-0.2.7/lib/kontena/machine/vagrant/master_provisioner.rb:66:in `block in run!'
  /var/lib/gems/2.3.0/gems/kontena-cli-1.2.2/lib/kontena/cli/spinner.rb:138:in `spin'
  /var/lib/gems/2.3.0/gems/kontena-cli-1.2.2/lib/kontena/cli/spinner.rb:186:in `spinner'
  /home/steven/.kontena/gems/2.3.1/gems/kontena-plugin-vagrant-0.2.7/lib/kontena/machine/vagrant/master_provisioner.rb:65:in `run!'
  /home/steven/.kontena/gems/2.3.1/gems/kontena-plugin-vagrant-0.2.7/lib/kontena/plugin/vagrant/master/create_command.rb:17:in `execute'
  /var/lib/gems/2.3.0/gems/kontena-cli-1.2.2/lib/kontena/command.rb:200:in `run'
  /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /var/lib/gems/2.3.0/gems/kontena-cli-1.2.2/lib/kontena/command.rb:200:in `run'
  /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /var/lib/gems/2.3.0/gems/kontena-cli-1.2.2/lib/kontena/command.rb:200:in `run'
  /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /var/lib/gems/2.3.0/gems/kontena-cli-1.2.2/lib/kontena/command.rb:200:in `run'
  /var/lib/gems/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
  /var/lib/gems/2.3.0/gems/kontena-cli-1.2.2/bin/kontena:17:in `<top (required)>'
  /usr/local/bin/kontena:23:in `load'
  /usr/local/bin/kontena:23:in `<main>'
```
Am I doing something wrong? Because I would assume the process walked through on the quick start guide, would be working like a well oiled machine. :confused: 

# Edit 1
when running Vagrant directly, I get no errors, and it seems to start as expected
```~/.kontena/vagrant_master $ vagrant up
Bringing machine 'home' up with 'virtualbox' provider...
==> home: Importing base box 'coreos-stable'...
==> home: Matching MAC address for NAT networking...
==> home: Checking if box 'coreos-stable' is up to date...
==> home: Setting the name of the VM: home
==> home: Clearing any previously set network interfaces...
==> home: Preparing network interfaces based on configuration...
    home: Adapter 1: nat
    home: Adapter 2: hostonly
==> home: Forwarding ports...
    home: 22 (guest) => 2222 (host) (adapter 1)
==> home: Running 'pre-boot' VM customizations...
==> home: Booting VM...
==> home: Waiting for machine to boot. This may take a few minutes...
    home: SSH address: 127.0.0.1:2222
    home: SSH username: core
    home: SSH auth method: private key
==> home: Machine booted and ready!
==> home: Setting hostname...
==> home: Configuring and enabling network interfaces...
==> home: Running provisioner: file...
==> home: Running provisioner: shell...
    home: Running: inline script
~/.kontena/vagrant_master $ 
```

# Edit 2
If i access the VM, when the console going into it's loop awaiting something, the vm has a tty waiting for 
'host' login name. The VM definitely seems to be provisioned correctly. However I cannot add any grids or nodes because there is no entry for the master node.

```  
kontena grid create testing
 [error] ArgumentError : You are not logged into a Kontena Master. Use: kontena master login
         Rerun the command with environment DEBUG=true set to get the full exception
```
```
kontena master login
 [error] URL not specified and current master not selected
```

no entry 
```
kontena master list 
Name                     Url
```

**Comment by jnummelin** [comment] 2017-06-05 10:49
Can you ssh into the created vagrant box? If yes, then check `docker ps -a`if that list contains kontena services. It should have three, ´kontena-server-api`, `kontena-mongodb` and `kontena-haproxy`.

If those are not around, then check `journalctl --identifier=coreos-cloudinit` if there are any errors from the provisioning.

Also check `journalctl -xe` for overall system logs.

The reason I'm suspecting the CLI "hangs" is that for some reason the master components are not spinning up as expected. The CLI waits for getting a "ping" through to the new master while provisioning.

**Comment by stvndall** [comment] 2017-06-05 17:25
Hi @jnummelin I did see that request when going through the plugin yesterday. I will get the stats when I have a moment, and feed them back :)

However surely there should be some kind of stderr stream coming back. I had to go into debug mode to find I had the wrong version of vbox on my machine, the console status kept spinning. It seems a little to optimistic :smile:

**Comment by jnummelin** [comment] 2017-06-05 20:36
The slow VM networking is the culprit as I assumed. We've seen similar behaviour in some envs in the past. So basically the issue is that the systemd units that spawn Kontena containers up do a `docker pull`naturally as a `PreExec` step. And now that step timeouts. :/

https://github.com/kontena/kontena/issues/1960

If you open VirtualBox GUI and see the Masters network settings, do you see an option to set the `Adapter type` (under advanced) to `Paravirtualized Network (virtio)`? Googling around suggests that using virtio has solved this kind of slow network issues for lot of vbox users. It seems that on my OSX at least virtio is default, at least I don't remember changing it ever. :)
![image](https://cloud.githubusercontent.com/assets/3205505/26802038/aedcfe5a-4a47-11e7-9d74-f921107ea2d9.png)

Another way to set the option is through vbox manage cli, `VBoxManage modifyvm YourMachineName --nictype1 virtio`

**Comment by stvndall** [comment] 2017-06-06 19:01
Hey there,

Thanks for the suggestions. Interestingly my VM is already running as Virtio-net for the network. I will give this a shot on a more beefy machine tomorrow. I can't seem to get the docker compose option to work either though. But I will revert with the details of the run on the stronger machine, good or bad. :)

**Comment by stvndall** [comment] 2017-06-12 17:32
I still can't get this container to start correctly with Vagrant. and docker compose seems to start, but the quick start guide doesn't explain how to connect the master node from the compose scripts to the kontena cli. I may have missed something

**Comment by jakolehm** [comment] 2017-06-12 18:35
@stvndall you can login to "composed master" using following command:
`kontena master login --code loginwiththiscodetomaster --name local http://localhost`

Replace "loginwiththiscodetomaster" with proper code (if you changed that in docker-compose.yml).

**Comment by SpComb** [comment] 2017-06-19 13:51
Closing the `kontena master create` systemd service docker pull timeout error in favor of #1960

**Closed by SpComb** 2017-06-19 13:51 UTC
Labels: question
