### ISSUE TITLE
Injected vault secrets to behave more like environment variables

### ISSUE THREAD

**Issue by christofferh** [kontena/kontena#651] opened 2016-05-04 06:55 UTC
Currently one needs to re-`deploy` a service/app in order for it to get the current secret value.
I propose that it should behave like normal environment variables and only require a `restart` for them to propagate. 

Issue:

```
kontena vault update MY_SECRET verysecret
kontena service restart service_with_my_secret_as_env
```

Expected result:
service_with_my_secret_as_env to restart and get the updated `MY_SECRET`

Actual result:
service_with_my_secret_as_env restarts and still uses the old `MY_SECRET`

Current workaround:
`kontena service deploy service_with_my_secret_as_env --force`

**Comment by jakolehm** [comment] 2016-05-06 04:46
Duplicate of #650

**Closed by jakolehm** 2016-05-06 04:46 UTC
