### ISSUE TITLE
CLI: can't modify frozen string when node is joining

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2794] opened 2017-09-12 07:57 UTC
```
    while true; do
      echo "waiting for moby.."
      [ "$(kontena node ls -q)" = "moby" ] && break
      sleep 1
    done

    kontena node ls
```

```
Creating kontena-agent ... done
waiting for moby..
waiting for moby..
waiting for moby..
waiting for moby..
waiting for moby..
 [error] RuntimeError : can't modify frozen String
         See /Users/mpa/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
waiting for moby..
NAME     VERSION   STATUS   INITIAL   LABELS
⊛ moby   1.3.4     online   1 / 1     -
```

related? https://github.com/kontena/kontena/issues/2414

**Comment by kke** [comment] 2017-09-12 08:06
Backtrace of exception in kontena.log?

**Comment by matti** [comment] 2017-09-12 10:20
```
E, [2017-09-12T13:19:46.616590 #65250] ERROR -- CLI: can't modify frozen String (RuntimeError)
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/indentation.rb:43:in `insert'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/indentation.rb:43:in `insert_indentation'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/indentation.rb:29:in `indent'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:241:in `insert_indent'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:314:in `render_row'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:292:in `block in render_rows'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:291:in `each'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:291:in `each_with_index'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:291:in `each'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:291:in `map'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:291:in `render_rows'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:251:in `render_data'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer/basic.rb:205:in `render'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer.rb:96:in `render'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table/renderer.rb:77:in `render_with'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table.rb:451:in `render_with'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/tty-table-0.8.0/lib/tty/table.rb:425:in `render'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.3.4/lib/kontena/cli/table_generator.rb:73:in `render'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.3.4/lib/kontena/cli/table_generator.rb:35:in `generate_table'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.3.4/lib/kontena/cli/table_generator.rb:39:in `print_table'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.3.4/lib/kontena/cli/nodes/list_command.rb:78:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.3.4/lib/kontena/command.rb:201:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.3.4/lib/kontena/command.rb:201:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.3.4/lib/kontena/command.rb:201:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
/opt/kontena/embedded/lib/ruby/gems/2.1.0/gems/kontena-cli-1.3.4/bin/kontena:18:in `<top (required)>'
/opt/kontena/embedded/bin/kontena:23:in `load'
/opt/kontena/embedded/bin/kontena:23:in `<main>'
```

**Comment by kke** [comment] 2017-09-15 06:03
I can't reproduce this on current git master

**Comment by matti** [comment] 2017-09-15 06:40
let’s keep this open until 1.4 is out - my automation will check for it

**Comment by SpComb** [comment] 2017-10-09 14:36
While it's still unclear exactly how `kontena node ls -q` is failing on what frozen string (the backtrace doesn't tell what frozen string it's mutating), I'm closing this with the assumption that this issue no longer affects 1.4, because the node joining process in the server changed in #2694 to always have a name available.

Please re-open if it still happens with 1.4.

The real fix would be for `tty-table` to not mutate strings when indenting, the workaround would be to figure out what string it's trying to mutate, and replace it with an unfrozen copy.

**Closed by SpComb** 2017-10-09 14:36 UTC
Labels: bug, cli
