### ISSUE TITLE
Stack upgrade did not update image url

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1670] opened 2017-01-17 20:52 UTC
Steps:

1. Installed a basic 'redis-cache' stack then noticed the registry url was incorrect (used $grid instead of $GRID so the url was `registry..kontena.local/...`).
2. Updated the yml file 'image:' for a couple services and incremented the version number and then ran `kontena stack upgrade kontena-redis-cache.yml`.
3. Ran `kontena stack show redis-cache`.

Result: The version was updated but the image urls were not.
Expected: The image urls in the installed stack reflect the updates made to the yml file.

Note, removing the stack and re-installing it showed the expected urls.

**Comment by SpComb** [comment] 2017-01-18 08:06
> ...and then ran `kontena stack upgrade ...`

Yes, point of confusion. You need to run `kontena stack upgrade --deploy` (or the equivalent `kontena stack upgrade && kontena stack deploy`) to actually update the kontena services and service containers. With just a `stack upgrade` without deploying, existing stack services will not yet be updated.

Also note that the `kontena stack show` command actually shows the same per-service data as `kontena service show`.

**Comment by SpComb** [comment] 2017-01-18 08:20
I think it would make more sense for `kontena stack upgrade` to actually update the server's service models, such that `kontena service show ...` would should the new service configurations, and you could then e.g. use `kontena service deploy ...` to deploy those to the grid service containers.

ATM `kontena stack upgrade` without `--deploy` is just confusing, because it doesn't actually do anything that would have any observable effect in the CLI? Internally, it creates a new `StackRevision` but you can't actually see that anywhere in the CLI.

**Comment by colinmollenhour** [comment] 2017-01-18 14:34
> I think it would make more sense for kontena stack upgrade to actually update the server's service models, such that kontena service show ... would should the new service configurations, and you could then e.g. use kontena service deploy ... to deploy those to the grid service containers.

As a user not knowing anything about internals I think that is what I was expecting; that an install of version 0.5.0 followed by an upgrade to 0.5.1 would be the equivalent to an install of 0.5.1.

**Comment by counterbeing** [comment] 2017-01-20 17:42
This sounds like a duplicate of one I opened a few days ago #1659. Seems they can be merged, and it seems that this could be as simple as documentation, but it may also be cause for come CLI changes.

**Comment by jnummelin** [comment] 2017-02-06 21:45
1.1.0 mitigates this now as the stack is deployed by default when installing or upgrading.

**Comment by colinmollenhour** [comment] 2017-02-07 17:25
So what does `kontena stack upgrade --no-deploy` actually do then? Seems the issue still exists, it is just no longer the default behavior.

**Comment by jnummelin** [comment] 2017-02-08 09:01
Stack upgrade creates a new revision of the stack. The installed stack can be thought of like a blueprint for the services. Only when you deploy a stack the blueprint is transferred into actual service configurations. Then again, service definition is also kinda blueprint and when the services are deployed, the actual containers "implement" that blueprint.

The longer term vision is to enable for example rollbacks and other such features with this version/blueprint functionality. 

Any ideas how to make this more clear and transparent for the user are welcome. :) Now it's obvious that it is somewhat confusing. :/

**Comment by colinmollenhour** [comment] 2017-02-08 15:39
Thanks for the explanation. Perhaps some different terminology would help? E.g. instead of install/upgrade it could be:

* stage (create blueprint for stack services - equivalent to `upgrade --no-deploy`)
* deploy (add/remove/modify services based on staged blueprint)
* install = stage + deploy

**Comment by counterbeing** [comment] 2017-02-08 20:29
I like that @colinmollenhour. I am unsure about the term `stage` though, makes me think of a staging environment or something, which it is not.  But, I like it better than what we have currently. Upgrade and deploy have almost the same meaning to me.

**Comment by SpComb** [comment] 2017-05-12 09:45
This is less of an issue with  #1737 to change `kontena stack install` and `kontena stack upgrade` to also run `kontena stack deploy` by default.

However, there are still some usecases for `kontena stack upgrade --no-deploy`, and those are currently not possible because of this behavior. Filed a new issue for that design question:  #2311

**Closed by SpComb** 2017-05-12 09:45 UTC
Labels: documentation
