### ISSUE TITLE
kontena-ipam-plugin fails in new AWS node

### ISSUE THREAD

**Issue by mudspot** [kontena/kontena#1811] opened 2017-02-08 06:46 UTC
Kontena Version: 1.1.0

Steps
1. Create new node on AWS with `kontena aws  node create....`
2. SSH into the node
3. docker ps
Will show that kontena-ipam-plugin keeps restarting
4. docker logs <kontena_ipam_plugin_container_id> shows

Using rack adapter
bundler: failed to load command: thin (/usr/bin/thin)
Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:2379 (Connection refused - connect(2) for "127.0.0.1" port 2379)
  /usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
  /usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
  /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
  /usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
  /usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
  /usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
  /usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
  /usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
  /usr/lib/ruby/gems/2.3.0/gems/etcd-0.3.0/lib/etcd/client.rb:111:in `api_execute'
  /app/app/etcd_client.rb:27:in `version'
  /app/app/etcd_client.rb:22:in `initialize'
  /app/config.ru:11:in `new'
  /app/config.ru:11:in `block in <main>'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
  /usr/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
  /app/config.ru:1:in `new'
  /app/config.ru:1:in `<main>'
  /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:33:in `eval'
  /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:33:in `load'
  /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/rack/adapter/loader.rb:42:in `for'
  /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:170:in `load_adapter'
  /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/controllers/controller.rb:74:in `start'
  /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:200:in `run_command'
  /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/lib/thin/runner.rb:156:in `run!'
  /usr/lib/ruby/gems/2.3.0/gems/thin-1.7.0/bin/thin:6:in `<top (required)>'
  /usr/bin/thin:23:in `load'
  /usr/bin/thin:23:in `<top (required)>'

**Comment by jnummelin** [comment] 2017-02-08 07:01
That is usually merely a symptom of something else. Ipam plugin tries to connect the local etcd instance on 127.0.0.1:2379 so it seems that etcd is not happy now. This may be caused by weave not starting up properly, there's a know rare bug in weave that makes it just crash on startup.

So check following to get clues on possible root cause:
`docker logs weave`
`ip addr show dev weave`, should show address `10.81.0.x`
`docker logs kontena-etcd`

**Comment by mudspot** [comment] 2017-02-08 07:14
Found the root cause

Say if I already have a node named `hello-world`, and then I create another node with the same name `hello-world`, the second node will get confused and the above-reported symptom appears.

REMEDY: Take care of node names (at least on AWS)

**Comment by jnummelin** [comment] 2017-02-09 11:58
Although you were able to solve the issue, I'm still interested how the name messed up things. :) AFAIK the name is not used within Kontena as unique and if you happen to have same hostname for many nodes, they get assigned <node_name>-i name, where i refers to a running number. Instead the nodes are (internally on master) identified by the Docker ID of the node.

How did you create the node in AWS side?

**Comment by jnummelin** [comment] 2017-03-15 08:32
Let's close this and re-open and examine more if we see this again.

**Closed by jnummelin** 2017-03-15 08:32 UTC
